### ISSUE TITLE
ueditor的action参数与rails的冲突

### ISSUE THREAD

**Issue by jstdoit** [doabit/baidu_ueditor_rails#3]
你好！现在我遇到个问题，ueditor的配置请求时区分请求的时候不是用的`action`这个名称吗？跟rails的冲突了，有什么好办法解决吗？

**Comment by doabit** [comment]
是的，我改成了uaction，不可以用action
https://github.com/doabit/baidu_ueditor_rails/blob/0.2.0/app/controllers/baidu_ueditor_rails/assets_controller.rb#L20

**Comment by jstdoit** [comment]
好的，谢谢
